version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'pharma'
      MYSQL_USER: 'pharma'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    restart: always
    volumes:
      - ./my-db:/var/lib/mysql